# -*- coding: utf-8 -*-
"""app.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1H6_g9KjUz3TC_g-E5slbsYWsSa61FqS4
"""

import streamlit as st
import pandas as pd
import io # Import io for buffer handling

# Import your custom functions
from eda_functions import run_eda
from model_functions import (
    preprocess_data_for_models,
    run_linear_regression,
    run_prophet_model,
    run_lstm_model,
    run_lightgbm_model
)
from optimization_functions import run_optimization
from concept_drift_functions import run_concept_drift_check

# --- Page Configuration ---
st.set_page_config(
    page_title="Phân tích & Dự báo Doanh số Bán lẻ",
    layout="wide",
    initial_sidebar_state="expanded"
)

st.title("Ứng dụng Phân tích & Dự báo Doanh số Bán lẻ")
st.markdown("""
    Ứng dụng này cung cấp các phân tích khám phá dữ liệu (EDA),
    dự báo doanh số bằng nhiều mô hình (Linear Regression, Prophet, LSTM, LightGBM),
    tối ưu hóa tồn kho, và kiểm tra concept drift.
""")

# --- Sidebar Navigation ---
st.sidebar.title("Chức năng")
analysis_option = st.sidebar.radio(
    "Chọn loại phân tích:",
    ["EDA - Phân tích Dữ liệu",
     "Dự báo Doanh số (Model Training)",
     "Tối ưu hóa Tồn kho",
     "Kiểm tra Concept Drift"]
)

# --- Data Loading (Global for all modules) ---
def check_file_exists(file_path):
    """Check if file exists and return appropriate path"""
    import os
    if os.path.exists(file_path):
        return file_path
    # Try alternative paths
    alternatives = [
        f"data/{file_path}",
        f"./{file_path}",
        file_path
    ]
    for alt_path in alternatives:
        if os.path.exists(alt_path):
            return alt_path
    return file_path  # Return original if none found

EDA_DATA_PATH = check_file_exists('final_dataset.csv')
MODEL_TRANSACTION_DATA = check_file_exists('transaction_data_2023_2024_updated.csv')
MODEL_PROMOTION_DATA = check_file_exists('promotion_data.csv')
MODEL_STORE_DATA = check_file_exists('store_info_data_2023_2024_updated.csv')
OPT_STORE_INFO_DATA = check_file_exists('store_info_data_2023_2024_updated.csv')
OPT_TRANS_INFO_DATA = check_file_exists('transaction_data_2023_2024_updated.csv')
CONCEPT_DRIFT_DATA = check_file_exists('final_dataset.csv')


# --- Main Content Area based on Selection ---

if analysis_option == "EDA - Phân tích Dữ liệu":
    st.header("Phân tích Dữ liệu Khám phá (EDA)")
    st.info(f"Đang sử dụng dữ liệu từ: `{EDA_DATA_PATH}`")
    with st.spinner('Đang chạy EDA...'):
        # Pass st object and data path to EDA function
        run_eda(df_path=EDA_DATA_PATH, st=st)
    st.success("EDA hoàn tất!")

elif analysis_option == "Dự báo Doanh số (Model Training)":
    st.header("Dự báo Doanh số")
    st.info(f"Đang sử dụng dữ liệu từ: `{MODEL_TRANSACTION_DATA}`, `{MODEL_PROMOTION_DATA}`, `{MODEL_STORE_DATA}`")

    # Debug: Show available files
    import os
    st.write("**Debug - Files trong thư mục hiện tại:**")
    current_files = [f for f in os.listdir('.') if f.endswith('.csv')]
    st.write(current_files)

    st.markdown("""
        Chọn mô hình bạn muốn chạy để dự báo doanh số.
        Lưu ý: Các mô hình có thể mất một chút thời gian để huấn luyệnnnn
    """)

    # Preprocess data once for all models to avoid redundancy
    df_for_models = None
    with st.spinner('Đang tiền xử lý dữ liệu cho các mô hình...'):
        try:
            df_for_models = preprocess_data_for_models(
                transaction_path=MODEL_TRANSACTION_DATA,
                promotion_path=MODEL_PROMOTION_DATA,
                store_path=MODEL_STORE_DATA
            )
            st.success("Tiền xử lý dữ liệu hoàn tất.")
        except FileNotFoundError as e:
            st.error(f"❌ Lỗi: {str(e)}")
            st.info("💡 **Hướng dẫn khắc phục:**")
            st.write("1. Kiểm tra các file CSV có trong thư mục gốc của ứng dụng")
            st.write("2. Đảm bảo tên file chính xác:")
            st.write(f"   - `{MODEL_TRANSACTION_DATA}`")
            st.write(f"   - `{MODEL_PROMOTION_DATA}`")
            st.write(f"   - `{MODEL_STORE_DATA}`")
            st.stop()
        except Exception as e:
            st.error(f"❌ Lỗi không xác định: {str(e)}")
            st.stop()

    model_choice = st.selectbox(
        "Chọn mô hình dự báo:",
        ["Linear Regression", "Prophet", "LSTM", "LightGBM"]
    )

    if st.button(f"Chạy Mô hình {model_choice}"):
        if df_for_models is not None:
            if model_choice == "Linear Regression":
                run_linear_regression(df_for_models, st)
            elif model_choice == "Prophet":
                run_prophet_model(df_for_models, st)
            elif model_choice == "LSTM":
                run_lstm_model(df_for_models, st)
            elif model_choice == "LightGBM":
                run_lightgbm_model(df_for_models, st)
        else:
            st.error("Không thể tải hoặc tiền xử lý dữ liệu. Vui lòng kiểm tra đường dẫn file.")

elif analysis_option == "Tối ưu hóa Tồn kho":
    st.header("Tối ưu hóa Vận chuyển Tồn kho")
    st.info(f"Đang sử dụng dữ liệu từ: `{OPT_STORE_INFO_DATA}`, `{OPT_TRANS_INFO_DATA}`")
    st.markdown("""
        Chức năng này sẽ tính toán lượng sản phẩm cần vận chuyển giữa các cửa hàng
        và từ kho trung tâm để đáp ứng ngưỡng tồn kho tối thiểu, nhằm tối thiểu hóa quãng đường vận chuyển.
    """)
    if st.button("Chạy Tối ưu hóa"):
        run_optimization(
            store_info_path=OPT_STORE_INFO_DATA,
            trans_info_path=OPT_TRANS_INFO_DATA,
            st=st
        )

elif analysis_option == "Kiểm tra Concept Drift":
    st.header("Kiểm tra Concept Drift")
    st.info(f"Đang sử dụng dữ liệu từ: `{CONCEPT_DRIFT_DATA}`")
    st.markdown("""
        Chức năng này sử dụng Kolmogorov-Smirnov (KS) test để kiểm tra xem
        phân phối của 'Quantity_Sold' có thay đổi đáng kể giữa hai giai đoạn thời gian hay không.
    """)
    if st.button("Chạy kiểm tra Concept Drift"):
        run_concept_drift_check(df_path=CONCEPT_DRIFT_DATA, st=st)
