# -*- coding: utf-8 -*-
"""app.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1H6_g9KjUz3TC_g-E5slbsYWsSa61FqS4
"""

import streamlit as st
import pandas as pd
import io # Import io for buffer handling

# Import your custom functions
from eda_functions import run_eda
from model_functions import (
    preprocess_data_for_models,
    run_linear_regression,
    run_prophet_model,
    run_lstm_model,
    run_lightgbm_model
)
from optimization_functions import run_optimization
from concept_drift_functions import run_concept_drift_check

# --- Page Configuration ---
st.set_page_config(
    page_title="Phân tích & Dự báo Doanh số Bán lẻ",
    layout="wide",
    initial_sidebar_state="expanded"
)

st.title("Ứng dụng Phân tích & Dự báo Doanh số Bán lẻ")
st.markdown("""
    Ứng dụng này cung cấp các phân tích khám phá dữ liệu (EDA),
    dự báo doanh số bằng nhiều mô hình (Linear Regression, Prophet, LSTM, LightGBM),
    tối ưu hóa tồn kho, và kiểm tra concept drift.
""")

# --- Sidebar Navigation ---
st.sidebar.title("Chức năng")
analysis_option = st.sidebar.radio(
    "Chọn loại phân tích:",
    ["EDA - Phân tích Dữ liệu",
     "Dự báo Doanh số (Model Training)",
     "Tối ưu hóa Tồn kho",
     "Kiểm tra Concept Drift"]
)

# --- Data Loading (Global for all modules) ---
# Tải các file dữ liệu.
# QUAN TRỌNG: Khi triển khai, bạn cần đảm bảo các file CSV này nằm cùng thư mục với app.py
# hoặc trong một thư mục con mà bạn tham chiếu đúng đường dẫn.
EDA_DATA_PATH = 'Data/final_dataset.csv' # THÊM 'Data/'
MODEL_TRANSACTION_DATA = 'Data/transaction_data_2024_2025_updated - transaction_data_2024_2025_updated.csv' # THÊM 'Data/'
MODEL_PROMOTION_DATA = 'Data/promotion_data - promotion (1).csv' # THÊM 'Data/'
MODEL_STORE_DATA = 'Data/store_info_data_2024_2025_updated - store_info_data_2024_2025_updated.csv' # THÊM 'Data/'
OPT_STORE_INFO_DATA = 'Data/store_info_data_2023_2024_updated.csv' # THÊM 'Data/'
OPT_TRANS_INFO_DATA = 'Data/transaction_data_2023_2024_updated.csv' # THÊM 'Data/'
CONCEPT_DRIFT_DATA = 'Data/final_dataset.csv' # THÊM 'Data/'


# --- Main Content Area based on Selection ---

if analysis_option == "EDA - Phân tích Dữ liệu":
    st.header("Phân tích Dữ liệu Khám phá (EDA)")
    st.info(f"Đang sử dụng dữ liệu từ: `{EDA_DATA_PATH}`")
    with st.spinner('Đang chạy EDA...'):
        # Pass st object and data path to EDA function
        run_eda(df_path=EDA_DATA_PATH, st=st)
    st.success("EDA hoàn tất!")

elif analysis_option == "Dự báo Doanh số (Model Training)":
    st.header("Dự báo Doanh số")
    st.info(f"Đang sử dụng dữ liệu từ: `{MODEL_TRANSACTION_DATA}`, `{MODEL_PROMOTION_DATA}`, `{MODEL_STORE_DATA}`")

    st.markdown("""
        Chọn mô hình bạn muốn chạy để dự báo doanh số.
        Lưu ý: Các mô hình có thể mất một chút thời gian để huấn luyện.
    """)

    # Preprocess data once for all models to avoid redundancy
    with st.spinner('Đang tiền xử lý dữ liệu cho các mô hình...'):
        df_for_models = preprocess_data_for_models(
            transaction_path=MODEL_TRANSACTION_DATA,
            promotion_path=MODEL_PROMOTION_DATA,
            store_path=MODEL_STORE_DATA
        )
    st.success("Tiền xử lý dữ liệu hoàn tất.")

    model_choice = st.selectbox(
        "Chọn mô hình dự báo:",
        ["Linear Regression", "Prophet", "LSTM", "LightGBM"]
    )

    if st.button(f"Chạy Mô hình {model_choice}"):
        if df_for_models is not None:
            if model_choice == "Linear Regression":
                run_linear_regression(df_for_models, st)
            elif model_choice == "Prophet":
                run_prophet_model(df_for_models, st)
            elif model_choice == "LSTM":
                run_lstm_model(df_for_models, st)
            elif model_choice == "LightGBM":
                run_lightgbm_model(df_for_models, st)
        else:
            st.error("Không thể tải hoặc tiền xử lý dữ liệu. Vui lòng kiểm tra đường dẫn file.")

elif analysis_option == "Tối ưu hóa Tồn kho":
    st.header("Tối ưu hóa Vận chuyển Tồn kho")
    st.info(f"Đang sử dụng dữ liệu từ: `{OPT_STORE_INFO_DATA}`, `{OPT_TRANS_INFO_DATA}`")
    st.markdown("""
        Chức năng này sẽ tính toán lượng sản phẩm cần vận chuyển giữa các cửa hàng
        và từ kho trung tâm để đáp ứng ngưỡng tồn kho tối thiểu, nhằm tối thiểu hóa quãng đường vận chuyển.
    """)
    if st.button("Chạy Tối ưu hóa"):
        run_optimization(
            store_info_path=OPT_STORE_INFO_DATA,
            trans_info_path=OPT_TRANS_INFO_DATA,
            st=st
        )

elif analysis_option == "Kiểm tra Concept Drift":
    st.header("Kiểm tra Concept Drift")
    st.info(f"Đang sử dụng dữ liệu từ: `{CONCEPT_DRIFT_DATA}`")
    st.markdown("""
        Chức năng này sử dụng Kolmogorov-Smirnov (KS) test để kiểm tra xem
        phân phối của 'Quantity_Sold' có thay đổi đáng kể giữa hai giai đoạn thời gian hay không.
    """)
    if st.button("Chạy kiểm tra Concept Drift"):
        run_concept_drift_check(df_path=CONCEPT_DRIFT_DATA, st=st)
